---
# tasks file for brew.install

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap some kegs
  homebrew_tap: tap="{{ item }}"
    state=present
  with_items:
    - ethereum/ethereum
    # - homebrew/completions
    # - homebrew/binary

- name: Install some brews
  homebrew: name={{ item }}
    state=present
  with_items:
    - autossh
    - bash-git-prompt
    - coreutils
    - curl
    - dnstracer
    - fpp
    - gdbm
    - git
    - git-lfs
    - gnupg
    - gnu-tar
    - go
    - htop-osx
    - httpie
    - ipcalc
    - libevent
    - libtool
    - libyaml
    - makedepend
    - mtr
    - ncdu
    - npm
    - openssl
    - packer
    - packer-completion
    - pcre
    - pkg-config
    - postgresql
    - readline
    - s3cmd
    - ssh-copy-id
    - sysdig
    - todo-txt
    - tree
    - xz
    - wget
    - whois
