---
# tasks file for brew.install

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap some kegs
  homebrew_tap: tap="{{ item }}"
    state=present
  with_items:
    - ethereum/ethereum
    # - homebrew/completions
    # - homebrew/binary

- name: Install some brews
  homebrew: name={{ item }}
    state=present
  with_items:
    - ansible
    - ansible-galaxy
    - ansible-lint
    - autossh
    - bash-completion
    - bash-git-prompt
    - cask
    - coreutils
    - curl
    - dnstracer
    - fpp
    - fzf
    - gdbm
    - git
    - git-lfs
    - gnupg
    - gnu-tar
    - gnutls
    - go
    - hadolint
    - htop-osx
    - httpie
    - ipcalc
    - jq
    - libevent
    - libtool
    - libyaml
    - makedepend
    - mtr
    - ncdu
    - npm
    - openssl
    - packer
    - packer-completion
    - pcre
    - pkg-config
    - postgresql
    - python
    - python3
    - readline
    - s3cmd
    - ssh-copy-id
    - sysdig
    - terraform
    - tflint
    - thefuck
    - tmux
    - todo-txt
    - tree
    - unbound
    - wget
    - whois
    - xz
    - yamllint
